// Exports ABIs from Foundry artifacts so the relayer, indexer, automation and web app never hand-copy them.
// Writes: contracts/abi/<Name>.json and contracts/ts/abi.ts (typed `as const` for viem).
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTRACTS = ["Circle", "CircleFactory", "CreditRegistry", "TurnAccount", "TurnKeeper", "MockAUSD"];

mkdirSync(join(root, "abi"), { recursive: true });
mkdirSync(join(root, "ts"), { recursive: true });

let ts = "// Generated by contracts/scripts/export-abis.mjs — do not edit.\n\n";
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
  writeFileSync(join(root, "abi", `${name}.json`), JSON.stringify(artifact.abi, null, 2) + "\n");
  const id = name[0].toLowerCase() + name.slice(1);
  ts += `export const ${id}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, "ts", "abi.ts"), ts);
console.log(`exported ${CONTRACTS.length} ABIs`);
